import type { Metadata } from 'next'
import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata: Metadata = {
  title: 'Tesla Green Charge',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="charset" content="utf-8" />
      </head>
      <body>
        <div className="container my-5">
          {children}
        </div>
      </body>
    </html>
  )
}
