#!/bin/sh
TESLA_API_TOKEN="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InE0dHg3Q1UyYzI2V1BiemwxZjZjanM3QnhzayJ9.eyJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJzdWIiOiIxOTJiMzBjZS1mMTZlLTQ2ZTEtOWQ3Yy1kNDAzYjczYWY3YjkiLCJpc3MiOiJodHRwczovL2F1dGgudGVzbGEuY29tL29hdXRoMi92My9udHMiLCJhenAiOiJlOTk0MWYwOGUwZDYtNGMyZi1iOGVlLTI5MTA2MGVjNjQ4YSIsImF1ZCI6WyJodHRwczovL2F1dGgudGVzbGEuY29tL29hdXRoMi92My9jbGllbnRpbmZvIiwiaHR0cHM6Ly9mbGVldC1hcGkucHJkLmV1LnZuLmNsb3VkLnRlc2xhLmNvbSJdLCJleHAiOjE3MDU5ODUzNTgsImlhdCI6MTcwNTk1NjU1OCwic2NwIjpbInZlaGljbGVfZGV2aWNlX2RhdGEiLCJ2ZWhpY2xlX2NtZHMiLCJ2ZWhpY2xlX2NoYXJnaW5nX2NtZHMiLCJvcGVuaWQiXX0.fQZJElugPQpQv-sBavzPUpwZMwOIRz8WdUWOjSRMjv7wlRwxyuvG-o_9KwMNrDNl0vUYkQT27ri06v3DD9RI1OUcw69coLQY3wPeMOAHYis6xq-VCufpGBvIyvUQQN-tputMH214JC-rJTQoWokohG3c1RopKh3VUIf-CzbvwWU8Qh75NswNJygpBm71o5hTeN251tR8rmAWzKFDHVNC-MLpXZWjwV7hrEocBMmK_yes9klKzkAWSeHDWBxSqC8N8GI_jyA96w3LtUsN6Mf3HdGPr1E-cbBLmENca17xdcERGDLJmxrtAmJFBl0JO7NpseI2HGEZl0iYPRnlYuwoJw"
AUDIENCE="https://fleet-api.prd.eu.vn.cloud.tesla.com"
# Partner authentication token request
curl -v --header 'Content-Type: application/json' \
  --header "Authorization: Bearer $TESLA_API_TOKEN" \
  --data '{"domain":"chargebot.io"}' \
  "${AUDIENCE}/api/1/partner_accounts"