name: Build Docker Image

on: [pull_request, workflow_dispatch, push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  test:
    runs-on: ubuntu-latest
    container: golang:1.22-bookworm
    steps:
    - uses: actions/checkout@v4
    - name: build libsodium (dep of libzmq)
      run: |
        mkdir /build
        cd /build
        wget https://github.com/jedisct1/libsodium/releases/download/1.0.19-RELEASE/libsodium-1.0.19.tar.gz
        tar -xzvf libsodium-1.0.19.tar.gz
        /build/libsodium-stable
        ./configure --disable-shared --enable-static
        make -j`nproc`
        make install
    - name: build libzmq (dep of zmq datastore)
      run: |
        mkdir /build
        cd /build
        wget https://github.com/zeromq/libzmq/releases/download/v4.3.5/zeromq-4.3.5.tar.gz
        tar -xvf zeromq-4.3.5.tar.gz
        /build/zeromq-4.3.5
        ./configure --enable-static --disable-shared --disable-Werror
        make -j`nproc`
        make install
    - name: Install dependencies
      run: go get -d -v ./...
    - name: Run tests
      run: go test -cover -v

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Log into registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest